name: ci
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  collector:
    runs-on: ubuntu-latest
    steps:
      - name: Setup env
        run: |
          JAEGER_VERSION=1.38.1
          echo "JAEGER_VERSION=$JAEGER_VERSION" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Make app dir
        run: mkdir -p appDir
      - name: Dowload bin files
        run: wget https://github.com/jaegertracing/jaeger/releases/download/v${{ env.JAEGER_VERSION }}/jaeger-${{ env.JAEGER_VERSION }}-linux-amd64.tar.gz
      - name: Extract files
        run: tar -xf jaeger-${{ env.JAEGER_VERSION }}-linux-amd64.tar.gz -C /appDir
